---
apiVersion: v1
kind: Secret
metadata:
  name: wireguard
  namespace: wireguard
type: Opaque
stringData:
  wg0.conf.template: |
    [Interface]
    PrivateKey = oG2sa0u9qJGWGC8+vtXRsLtI0IxXKtaYzGlpPzqD91k=
    Address = 172.16.16.10/20
    DNS = 1.1.1.1

    [Peer]
    PublicKey = CSB59ZuD/YVwKWRpVfRpzhirVxfAr36E5770/JDqDx4=
    AllowedIPs = 0.0.0.0/0
    Endpoint = 12.12.12.12:51820
    PersistentKeepalive = 25
